Repository Seravo/seravo-plugin, pull requests merged in 2021-06, with the labels that each got.

#530 Fix HTTP stats latest months logic
  modules/dashboard-widgets.php
Labels: enhancement

#529 Add GUI for wp-db-optimize (Closes: #523)
  js/database.js
  languages/seravo-fi.mo
  languages/seravo-fi.po
  languages/seravo.pot
  lib/db-cleanup-ajax.php
  modules/database.php
Labels: enhancement

#531 Check if PHP compatibility log file exists
  modules/logs.php
Labels: bug, enhancement

#533 Check that filepath is valid when reading logs
  modules/logs.php
Labels: bug, enhancement

#545 Redesign postbox handling
  js/postbox/seravo-ajax.js
  js/postbox/seravo-postbox.js
  lib/postbox/ajax.php
  lib/postbox/component.php
  lib/postbox/handler.php
  lib/postbox/postbox.php
  lib/postbox/template.php
  modules/backups.php
  modules/database.php
  modules/domains.php
  modules/security.php
  modules/sitestatus.php
  modules/toolbox.php
  modules/upkeep.php
  seravo-plugin.php
  style/common.css
Labels: codebase, enhancement

#546 Add common css file
  style/common.css
Labels: enhancement

#547 Add multiple helpers to templates
  lib/postbox/template.php
Labels: enhancement

#554 Use autoload on classes api, helpers & list-table (Related: #543)
  composer.json
  seravo-plugin.php
  src/lib/api.php
  src/lib/domain-tables.php
  src/lib/helpers.php
  src/lib/list-table.php
  vendor/composer/ClassLoader.php
  vendor/composer/LICENSE
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
Labels: codebase, enhancement

#556 Update authors
  composer.json
Labels: enhancement

#562 Rewrite database page widgets (Related: 544)
  src/lib/ajax/templates/button-command.php
  src/lib/ajax/templates/command-runner.php
  src/lib/db-cleanup-ajax.php
  src/lib/helpers.php
  src/lib/postbox/component/template.php
  src/modules/database.php
  style/common.css
  vendor/composer/ClassLoader.php
  vendor/composer/LICENSE
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
Labels: enhancement

#563 Misc improvements to template helpers
  src/lib/postbox/component/template.php
  style/common.css
Labels: enhancement
